Revert "Merge branch 'staging-sprint-3' into myrecipes-4"
This reverts commit f04c3d7ebac2c9f90e57608683e1c0b2baf080c2, reversing
changes made to 896b965b91f1d936817cfbf0320bf884f94c6228.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,6 +4,9 @@
 #runs the workflow on any push to any branch
 #also runs when any PR is opened or updated
 
+# Github Actions workflow to run the following CI checks:
+# unit tests, linting, and documentation generation
+
 on: [push, pull_request]
 
 jobs:
@@ -13,7 +16,7 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Set up Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
           node-version: 18
 
@@ -36,8 +39,15 @@ jobs:
         run: npm run htmlhint || touch htmlhint.failed
         continue-on-error: true
 
-      - name: Log if any linter failed
-        run: echo "Linters may have issues. Review the logs above"
+      - name: Generate JSDoc
+        run: npm run jsdoc
+
+      - name: Fail job if any linter failed
+        run: |
+          if [ -f eslint.failed ] || [ -f stylelint.failed ] || [ -f htmlhint.failed ]; then
+            echo "❌ One or more linters failed"
+            exit 1
+          fi
 
   test:
     runs-on: ubuntu-latest
@@ -55,7 +65,7 @@ jobs:
       - name: Run unit tests
         run: npm test
 
-  doc:
+  document:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -71,30 +81,20 @@ jobs:
       - name: Generate JSDoc
         run: npm run jsdoc
 
-  e2e:
+  format:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v2
 
       - name: Set up Node.js
-        uses: actions/setup-node@v4
-
+        uses: actions/setup-node@v3
         with:
           node-version: 18
 
       - name: Install dependencies
         run: npm ci
 
-      - name: Install Playwright Browsers
-        run: npx playwright install --with-deps
-
-      - name: Run Playwright E2E Tests
-        run: npx playwright test
-
-      - name: Upload Playwright Report on Failure
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: playwright-report
-          path: playwright-report/
+      - name: run Prettier
+        run: npm run prettier
+        continue-on-error: true
 
